spring:
  application:
    name: spring-csv-handler

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    baseline-on-migrate: true